Foi adicionado a página de personas e perfil de usuário
Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo pull request #36
Opened 2022-02-26 17:47 UTC by lorenzo7377

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?

- Foi criado o documento de personas e sobre o perfil de usuário

### Descrição
Foram colocadas as personas, as imagens de cada uma também, e foi criado um tópico sobre o perfil de usuário

Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #32  | Perfil de usuário e personas|

      

## Lista de controle:
- [x] Você verificou se não há outras [Solicitações de Pull](https://github.com/Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo/pulls) para a mesma atualização/alteração?

## Quem contribuiu?
@lorenzo7377

2022-02-26 23:19 UTC, klmurussi requested changes
![Captura de Tela (27)](https://user-images.githubusercontent.com/52364259/155862006-811af0fc-75e4-4bd3-a4d2-72e429351090.png)

imagens não aparecem

2022-02-26 23:22 UTC, klmurussi requested changes

2022-02-26 23:22 UTC, klmurussi commented on docs/index.md
> +<p style="text-indent: 20px; text-align: justify">Este repositório tem como objetivo documentar o projeto do grupo 2 da matéria de **Interação Humano Computador** da Universidade de Brasília, ministr
![Captura de Tela (25)](https://user-images.githubusercontent.com/52364259/155862039-6d3bdd59-943f-41fb-abde-e560cb71194b.png)

esse alinhamento justificado tira as outras coisinhas, como, link, negrito, tabela etc

2022-02-27 14:54 UTC, kayrocesar commented on docs/AnaliseRequisitos/PerfilUsuario/personas.md
> + | **Data**   | **Versão** | **Descrição**   |    **Autor(es)**  |
Não seria melhor seguir esse padrão aqui?
![padrao](https://user-images.githubusercontent.com/39713656/155887358-f1374784-0e06-4546-b33c-b817a9c04625.PNG)

2022-02-27 14:54 UTC, kayrocesar commented on docs/AnaliseRequisitos/PerfilUsuario/personas.md
> +<img src="../../../assets/img/perfilusuario.png">
corrigido

2022-02-27 15:28 UTC, lorenzo7377 commented on docs/AnaliseRequisitos/PerfilUsuario/personas.md
> + | **Data**   | **Versão** | **Descrição**   |    **Autor(es)**  |
uma revisão não é uma nova versão

2022-02-27 16:53 UTC, klmurussi commented
tudo correto do personas

2022-02-27 16:53 UTC, merged