Plan analise tarefas
Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo pull request #54
Opened 2022-03-16 13:16 UTC by klmurussi

## O que mudou?
### Qual foi a mudança significativa para que haja um Pull Request?
criação do documento de planejamento de análise de tarefas
-

### Descrição
Close:

| Issue |            Título            |
|-------|:----------------------------:|
| #52 | Elaborar documento de Planejamento da Avaliação da Análise de tarefas |

## Lista de controle:
- [x] Você verificou se não há outras [Solicitações de Pull](https://github.com/Interacao-Humano-Computador/2021.2-Prefeitura-de-Passo-Fundo/pulls) para a mesma atualização/alteração?

## Quem contribuiu?
@kayrocesar 
@klmurussi

2022-03-16 18:47 UTC, magnluiz commented on docs/DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/PlanejamentoAnaliseTarefas.md
> +<div style="text-align: justify"><b>Perfil do usuário: Cidadões da cidade de Passo Fundo que desejam obter algum tipo de alvarás ou licença.</b><br>
Trocar "Cidadões" por "Cidadãos"

2022-03-16 22:28 UTC, kayrocesar commented on docs/DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/PlanejamentoAnaliseTarefas.md
> +<div style="text-align: justify"><b>Perfil do usuário: Cidadões da cidade de Passo Fundo que desejam obter algum tipo de alvarás ou licença.</b><br>
Corrigido.

2022-03-17 00:24 UTC, SwampTG requested changes
Exceto pelos erros gramaticais, o documento está completo. Muito Bom!

2022-03-17 00:24 UTC, SwampTG commented on docs/DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/PlanejamentoAnaliseTarefas.md
> +    Na atividade de preparação, devem ser organizados os objetos do estudo e  o material de apoio. Os objetos do estudo consistem em: uma lista de tarefas investigadas e a sequência das ações que  o
* executar para concluir

2022-03-17 00:24 UTC, SwampTG commented on docs/DesignAvaliacaoDesenvolvimento/Nivel1/AnaliseTarefas/PlanejamentoAnaliseTarefas.md
> +<div style="text-align: justify">No método escolhido pelo grupo, a coleta de dados acontecerá por meio de percurso cognitivo, método de inspensão, onde o(s) inspetor(es) deve(m) se "colocar no lugar
* inspeção

2022-03-17 01:27 UTC, merged